### Crear usuario
POST http://localhost:8000/createuser
Content-Type: application/json

{
  "username": "tomi",
  "email": "tomi@example.com",
  "password": "clave123",
  "first_name": "Tomi",
  "last_name": "Apellido"
}

### Login con username
POST http://localhost:8000/login
Content-Type: application/json

{
  "identifier": "tomi",
  "password": "clave123"
}

### Login con email
POST http://localhost:8000/login
Content-Type: application/json

{
  "identifier": "tomi@example.com",
  "password": "clave123"
}

### Ruta protegida (requiere token del login)
GET http://localhost:8000/me
Authorization: Bearer {{token}}
